CREATE TABLE position
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    position_name varchar(100) NOT NULL
);

CREATE TABLE employee
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    position_id   BIGINT REFERENCES position (id) DEFAULT NULL,
    first_name    varchar(100) NOT NULL,
    last_name     varchar(100) NOT NULL
);

CREATE TABLE project
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name varchar(100) NOT NULL
);

CREATE TABLE employee_project
(
    employee_id BIGINT REFERENCES employee (id),
    project_id  BIGINT REFERENCES project (id)
);


-- Тестовые данные --
INSERT INTO position(position_name)
VALUES ('Разработчик'),
       ('Тестировщик');
INSERT INTO employee(first_name, last_name, position_id)
VALUES ('Василий', 'Васильев', 1),
       ('Алексей', 'Алексеев', 2),
       ('Андрей', 'Андреев', 2),
       ('Оксана', 'Архипова', 1);
INSERT INTO project(project_name)
VALUES ('Банк'),
       ('Сеть магазинов');
INSERT INTO employee_project(employee_id, project_id)
VALUES (1, 1),
       (2, 2),
       (3, 1),
       (4, 2);